
package ui;

import data.GestorEntidades;
import data.EscritorEntidades;
import model.Registrable;
import model.GuiaTuristico;
import model.Vehiculo;
import model.ColaboradorExterno;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Image;
import exceptions.DatoInvalidoException;
import java.util.List;
import util.LectorEntidades;
import model.RecursoAgencia;



/**
 * Ventana principal del sistema Llanquihue Tour.
 * Permite registrar, visualizar y almacenar
 * las entidades administradas por la agencia.
 *
 * @author Sergio Sandoval
 */

public class Test extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Test.class.getName());
    
    private final GestorEntidades gestorEntidades;

    /**
    * Crea la interfaz principal del sistema
    * Llanquihue Tour e inicializa sus componentes.
    */
    public Test() {
        initComponents();
        
        // Mantiene el tamaño fijo de la ventana para conservar el diseño de la interfaz.
        setResizable(false);
   
    // Colores de la interfaz
    getContentPane().setBackground(
            new java.awt.Color(140, 180, 210));

    jPanel2.setBackground(
            new java.awt.Color(195, 218, 235));

    jPanel3.setBackground(
            new java.awt.Color(195, 218, 235));

    jLabel2.setForeground(
            new java.awt.Color(0, 60, 125));

    jLabel2.setFont(
            new java.awt.Font(
                    "FreeSans",
                    java.awt.Font.BOLD,
                    40));

    gestorEntidades = new GestorEntidades();

    cargarEntidadesIniciales();

    txtAreaRegistros.setEditable(false);
    txtAreaRegistros.setLineWrap(true);
    txtAreaRegistros.setWrapStyleWord(true);

    setLocationRelativeTo(null);

    ImageIcon icono = new ImageIcon(
            getClass().getResource(
                    "/resources/logo.png"));

    Image imagen = icono.getImage().getScaledInstance(
            lbLogo.getWidth(),
            lbLogo.getHeight(),
            Image.SCALE_SMOOTH);

    lbLogo.setIcon(new ImageIcon(imagen));
    lbLogo.setText("");
        
    }
    
/**
 * Carga en el gestor las entidades almacenadas
 * en el archivo entidades.txt.
 */
private void cargarEntidadesIniciales() {

    List<Registrable> entidades =
            LectorEntidades.cargarEntidades(
                    "src/resources/entidades.txt"
            );

    for (Registrable entidad : entidades) {

        gestorEntidades.agregarEntidad(entidad);
    }
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbtipousuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JTextField();
        txtDatoEspecifico = new javax.swing.JTextField();
        btnAyuda = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnMostrarRegistros = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRegistros = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 36)); // NOI18N
        jLabel2.setText("Sistema Llanquihue Tour");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información específica:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 0, 15))); // NOI18N
        jPanel2.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        jLabel1.setText("Tipo de Registro:");

        cmbtipousuario.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        cmbtipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "Guía turístico", "Vehículo", "Colaborador externo" }));
        cmbtipousuario.addActionListener(this::cmbtipousuarioActionPerformed);

        jLabel3.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        jLabel4.setText("Identificador:");

        jLabel5.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        jLabel5.setText("Información específica:");

        txtNombre.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N

        txtIdentificador.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        txtIdentificador.addActionListener(this::txtIdentificadorActionPerformed);

        txtDatoEspecifico.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        txtDatoEspecifico.addActionListener(this::txtDatoEspecificoActionPerformed);

        btnAyuda.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        btnAyuda.setText("Ayuda ?");
        btnAyuda.addActionListener(this::btnAyudaActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatoEspecifico))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addComponent(txtNombre)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAyuda)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatoEspecifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jLabel5.getAccessibleContext().setAccessibleName("Información específica:");

        btnAgregar.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnMostrarRegistros.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        btnMostrarRegistros.setText("Mostrar Registros");
        btnMostrarRegistros.addActionListener(this::btnMostrarRegistrosActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros ingresados:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 0, 15))); // NOI18N
        jPanel3.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N

        txtAreaRegistros.setColumns(20);
        txtAreaRegistros.setRows(5);
        jScrollPane1.setViewportView(txtAreaRegistros);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnSalir.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        lbLogo.setFont(new java.awt.Font("FreeSans", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btnMostrarRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnMostrarRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel3.getAccessibleContext().setAccessibleName("Resgistros");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
    * Registra una nueva entidad utilizando
    * los datos ingresados por el usuario.
    *
    * @param evt evento generado por el boton
    */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
       if (cmbtipousuario.getSelectedIndex() == 0) {
        mostrarError("Debe seleccionar un tipo de registro.");
        cmbtipousuario.requestFocus();
        return;
    }

    String nombre = txtNombre.getText().trim();
    String identificador = txtIdentificador.getText().trim();
    String datoEspecifico = txtDatoEspecifico.getText().trim();

    if (nombre.isEmpty()
            || identificador.isEmpty()
            || datoEspecifico.isEmpty()) {

        mostrarError("Debe completar todos los campos.");
        return;
    }

    if (nombre.length() < 3) {
        mostrarError(
                "El nombre o la marca debe contener al menos 3 caracteres.");
        txtNombre.requestFocus();
        return;
    }

    if (datoEspecifico.length() < 3) {
        mostrarError(
                "La información específica debe contener al menos 3 caracteres.");
        txtDatoEspecifico.requestFocus();
        return;
    }

    String tipoRegistro =
            cmbtipousuario.getSelectedItem().toString();

    switch (tipoRegistro) {

        case "Guía turístico":
            identificador = identificador.toUpperCase();

            if (!identificador.matches("GUIA-\\d{3}")) {
                mostrarError(
                        "El código del guía debe tener el formato GUIA-001.");
                txtIdentificador.requestFocus();
                return;
            }
            break;

        case "Vehículo":
            identificador = identificador.toUpperCase();

            if (!identificador.matches("[A-Z]{4}-\\d{2}")) {
                mostrarError(
                        "La patente debe tener el formato ABCD-12.");
                txtIdentificador.requestFocus();
                return;
            }
            break;

        case "Colaborador externo":
            identificador = identificador.toUpperCase();

            if (!identificador.matches("COL-\\d{3}")) {
                mostrarError(
                        "El código debe tener el formato COL-001.");
                txtIdentificador.requestFocus();
                return;
            }
            break;

        default:
            return;
    }

    // Evitar identificadores repetidos
    for (Registrable registro
            : gestorEntidades.getEntidades()) {

        if (registro instanceof RecursoAgencia recurso
                && recurso.getIdentificador()
                        .equalsIgnoreCase(identificador)) {

            mostrarError(
                    "Ya existe un registro con ese identificador.");

            txtIdentificador.requestFocus();
            return;
        }
    }

    

    try {

    Registrable nuevoRegistro;

    switch (tipoRegistro) {

        case "Guía turístico":
            nuevoRegistro = new GuiaTuristico(
                    nombre,
                    identificador,
                    datoEspecifico
            );
            break;

        case "Vehículo":
            nuevoRegistro = new Vehiculo(
                    nombre,
                    identificador,
                    datoEspecifico
            );
            break;

        case "Colaborador externo":
            nuevoRegistro = new ColaboradorExterno(
                    nombre,
                    identificador,
                    datoEspecifico
            );
            break;

        default:
            return;
    }

    gestorEntidades.agregarEntidad(nuevoRegistro);
    
    EscritorEntidades.guardarEntidad(nuevoRegistro);

} catch (DatoInvalidoException e) {

    mostrarError(e.getMessage());
    return;
}
   
    JOptionPane.showMessageDialog(
            this,
            "Registro agregado correctamente.",
            "Operación exitosa",
            JOptionPane.INFORMATION_MESSAGE);

            limpiarFormulario();
            
       
            
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    
    /**
    * Muestra todas las entidades registradas
    * en el area de texto.
    *
    * @param evt evento generado por el boton
    */
    private void btnMostrarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarRegistrosActionPerformed
    if (gestorEntidades.getEntidades().isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "No existen registros ingresados.",
            "Sin registros",
            JOptionPane.INFORMATION_MESSAGE);

    txtAreaRegistros.setText("");
    return;
}

    StringBuilder resumen = new StringBuilder();

    for (Registrable registro : gestorEntidades.getEntidades()) {

    resumen.append(registro.mostrarResumen())
            .append("\n")
            .append("------------------------------")
            .append("\n");
     }

    txtAreaRegistros.setText(resumen.toString());
    txtAreaRegistros.setCaretPosition(0);    
    }//GEN-LAST:event_btnMostrarRegistrosActionPerformed

    
    /**
    * Limpia los datos ingresados en el formulario.
    *
    * @param evt evento generado por el boton
    */
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarFormulario();
    }
    
    
    
    /**
    * Limpia todos los controles del formulario y
    * deja la interfaz en su estado inicial.
    */     
    private void limpiarFormulario() {
        cmbtipousuario.setSelectedIndex(0);
        txtNombre.setText("");
        txtIdentificador.setText("");
        txtDatoEspecifico.setText("");

    jLabel3.setText("Nombre:");
    jLabel4.setText("Identificador:");
    jLabel5.setText("Información específica:");

    txtNombre.requestFocus();
}

    
/**
* Muestra un mensaje de error al usuario.
*
* @param mensaje texto del mensaje a mostrar
*/    
private void mostrarError(String mensaje) {

    JOptionPane.showMessageDialog(
            this,
            mensaje,
            "Dato inválido",
            JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    /**
    * Muestra una ayuda contextual segun el
    * tipo de registro seleccionado.
    *
    * @param evt evento generado por el boton
    */
    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        String mensaje;

        switch (cmbtipousuario.getSelectedItem().toString()) {

            case "Guía turístico":
            mensaje = """
            Especialidades:

            • Turismo aventura
            • Turismo cultural
            • Gastronomía
            • Ecoturismo
            • Senderismo
            """;
            break;

            case "Vehículo":
            mensaje = """
            Tipos de vehículo:

            • Automóvil
            • Van
            • Minibús
            • Bus
            • Camioneta
            """;
            break;

            case "Colaborador externo":
            mensaje = """
            Empresas:

            • Servicios Turísticos del Sur
            • Transportes Llanquihue
            • Turismo Patagonia
            • Hotel del Lago
            """;
            break;

            default:
            mensaje = "Seleccione primero un tipo de registro.";
            break;
        }

        JOptionPane.showMessageDialog(
            this,
            mensaje,
            "Ayuda",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void txtDatoEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoEspecificoActionPerformed
        
    }//GEN-LAST:event_txtDatoEspecificoActionPerformed

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        
    }//GEN-LAST:event_txtIdentificadorActionPerformed

    
    /**
    * Actualiza las etiquetas del formulario
    * segun el tipo de registro seleccionado.
    *
    * @param evt evento generado por el combo
    */
    private void cmbtipousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtipousuarioActionPerformed
        String tipo = cmbtipousuario.getSelectedItem().toString();

        switch (tipo) {
            case "Guía turístico":
            jLabel3.setText("Nombre:");
            jLabel4.setText("Código guía:");
            jLabel5.setText("Especialidad:");
            break;

            case "Vehículo":
            jLabel3.setText("Marca:");
            jLabel4.setText("Patente:");
            jLabel5.setText("Tipo de vehículo:");

            break;

            case "Colaborador externo":
            jLabel3.setText("Nombre:");
            jLabel4.setText("Código colaborador:");
            jLabel5.setText("Empresa:");
            break;

            default:
            jLabel3.setText("Nombre:");
            jLabel4.setText("Identificador:");
            jLabel5.setText("Información específica:");
            break;
        }
    }//GEN-LAST:event_cmbtipousuarioActionPerformed

    
    /**
    * Solicita confirmacion antes de cerrar
    * la aplicacion.
    *
    * @param evt evento generado por el boton
    */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Desea salir del sistema?",
            "Confirmar salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
           System.exit(0);
           
         }       
            
            
    }//GEN-LAST:event_btnSalirActionPerformed

  


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            
            
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Test().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarRegistros;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbtipousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JTextArea txtAreaRegistros;
    private javax.swing.JTextField txtDatoEspecifico;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables



}





